package golem:core@1.5.0 {
  interface types {
    type node-index = s32;

    type resource-id = u64;

    enum resource-mode {
      owned,
      borrowed,
    }

    variant wit-type-node {
      record-type(list<tuple<string, node-index>>),
      variant-type(list<tuple<string, option<node-index>>>),
      enum-type(list<string>),
      flags-type(list<string>),
      tuple-type(list<node-index>),
      list-type(node-index),
      option-type(node-index),
      result-type(tuple<option<node-index>, option<node-index>>),
      prim-u8-type,
      prim-u16-type,
      prim-u32-type,
      prim-u64-type,
      prim-s8-type,
      prim-s16-type,
      prim-s32-type,
      prim-s64-type,
      prim-f32-type,
      prim-f64-type,
      prim-char-type,
      prim-bool-type,
      prim-string-type,
      handle-type(tuple<resource-id, resource-mode>),
    }

    record named-wit-type-node {
      name: option<string>,
      owner: option<string>,
      %type: wit-type-node,
    }

    record wit-type {
      nodes: list<named-wit-type-node>,
    }

    record text-type {
      language-code: string,
    }

    record text-descriptor {
      restrictions: option<list<text-type>>,
    }

    record binary-type {
      mime-type: string,
    }

    record binary-descriptor {
      restrictions: option<list<binary-type>>,
    }

    variant element-schema {
      component-model(wit-type),
      unstructured-text(text-descriptor),
      unstructured-binary(binary-descriptor),
    }

    variant data-schema {
      %tuple(list<tuple<string, element-schema>>),
      multimodal(list<tuple<string, element-schema>>),
    }

    record uuid {
      high-bits: u64,
      low-bits: u64,
    }

    record component-id {
      uuid: uuid,
    }

    record uri {
      value: string,
    }

    variant wit-node {
      record-value(list<node-index>),
      variant-value(tuple<u32, option<node-index>>),
      enum-value(u32),
      flags-value(list<bool>),
      tuple-value(list<node-index>),
      list-value(list<node-index>),
      option-value(option<node-index>),
      result-value(result<option<node-index>, option<node-index>>),
      prim-u8(u8),
      prim-u16(u16),
      prim-u32(u32),
      prim-u64(u64),
      prim-s8(s8),
      prim-s16(s16),
      prim-s32(s32),
      prim-s64(s64),
      prim-float32(f32),
      prim-float64(f64),
      prim-char(char),
      prim-bool(bool),
      prim-string(string),
      handle(tuple<uri, u64>),
    }

    record wit-value {
      nodes: list<wit-node>,
    }

    record text-source {
      data: string,
      text-type: option<text-type>,
    }

    variant text-reference {
      url(string),
      inline(text-source),
    }

    type url = string;

    record binary-source {
      data: list<u8>,
      binary-type: binary-type,
    }

    variant binary-reference {
      url(url),
      inline(binary-source),
    }

    variant element-value {
      component-model(wit-value),
      unstructured-text(text-reference),
      unstructured-binary(binary-reference),
    }

    variant data-value {
      %tuple(list<element-value>),
      multimodal(list<tuple<string, element-value>>),
    }

    record value-and-type {
      value: wit-value,
      typ: wit-type,
    }

    record agent-id {
      component-id: component-id,
      agent-id: string,
    }

    type oplog-index = u64;

    record promise-id {
      agent-id: agent-id,
      oplog-idx: oplog-index,
    }

    record account-id {
      uuid: uuid,
    }

    parse-uuid: func(uuid: string) -> result<uuid, string>;
  }
}


