package wasi:clocks@0.2.12 {
  interface wall-clock {
    record datetime {
      seconds: u64,
      nanoseconds: u32,
    }

    now: func() -> datetime;
  }
  interface monotonic-clock {
    use wasi:io/poll@0.2.12.{pollable};

    type duration = u64;

    type instant = u64;

    now: func() -> instant;

    subscribe-duration: func(when: duration) -> pollable;
  }
}


